// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBpJzBPJiHOS-GQEcNBN91lKa2xLVChho',
    appId: '1:865510799447:web:73fc38c72fdf7514ad8b12',
    messagingSenderId: '865510799447',
    projectId: 'notesapp-flutlearn',
    authDomain: 'notesapp-flutlearn.firebaseapp.com',
    storageBucket: 'notesapp-flutlearn.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnwW8mjI0FXVuagnEhvk_VusREmUbI478',
    appId: '1:865510799447:android:961f67535b01a392ad8b12',
    messagingSenderId: '865510799447',
    projectId: 'notesapp-flutlearn',
    storageBucket: 'notesapp-flutlearn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWSlDXp3uUT4cJhK-0PjFwVc6FluOdW5s',
    appId: '1:865510799447:ios:b827a824f4e1fef3ad8b12',
    messagingSenderId: '865510799447',
    projectId: 'notesapp-flutlearn',
    storageBucket: 'notesapp-flutlearn.appspot.com',
    iosBundleId: 'com.flulearn.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWSlDXp3uUT4cJhK-0PjFwVc6FluOdW5s',
    appId: '1:865510799447:ios:b827a824f4e1fef3ad8b12',
    messagingSenderId: '865510799447',
    projectId: 'notesapp-flutlearn',
    storageBucket: 'notesapp-flutlearn.appspot.com',
    iosBundleId: 'com.flulearn.notesapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBpJzBPJiHOS-GQEcNBN91lKa2xLVChho',
    appId: '1:865510799447:web:a1009b015fee69b6ad8b12',
    messagingSenderId: '865510799447',
    projectId: 'notesapp-flutlearn',
    authDomain: 'notesapp-flutlearn.firebaseapp.com',
    storageBucket: 'notesapp-flutlearn.appspot.com',
  );
}
